name: Redis Rate Limiter Tests

on:
  pull_request:
  push:
    branches:
      - main
      - staging

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Run tests (no features)
        run: cargo test -- --show-output

      - name: Run tests (actix-web)
        run: cargo test --features actix-web -- --show-output

      - name: Run tests (tower)
        run: cargo test --features tower -- --show-output

      - name: Run tests (all features)
        run: cargo test --all-features -- --show-output
